LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls', namespace='library')),
    path('', include('library.urls', namespace='library')),
]

library/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.landingpage, name='landingPage'),
    path('home/', views.homePage, name='homePage'),
    path('team/', views.teamPage, name='team'),
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='signup'),
    path('profile/<str:username>', views.viewProfile.as_view(), name='viewProfile'),
    path('resetPassword', views.resetPassword.as_view(), name='resetPassword'),
    path('logout', views.Logout, name='logout'),
    path('uploadbarcode', views.uploadBarcode.as_view(), name="uploadBarcode"),
    path('search/', views.search, name='search'),
    path('rent/<str:barcode>', views.rent, name='rent'),
    path('returnbook/<str:barcode>/<str:prn>', views.return_book_superuser, name='returnBook')
]

library/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Member(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    prn = models.CharField(max_length=15)
    email = models.EmailField(max_length=200)
    #avatar = models.ImageField(default = 'avatar.png', upload_to='avatars/')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    #Choices for branch
    ELECTRONICS="ELN"
    ELECTRICAL="ELE"
    MECHANICAL="MECH"
    INFORMATION_TECHNOLOGY="IT"
    COMPUTER_SCIENCE="CS"
    CIVIL="CVL"
    BRANCH_CHOICES=[
        (ELECTRONICS,"Electronics"),
        (ELECTRICAL,"Electrical"),
        (MECHANICAL,"Mechanical"),
        (INFORMATION_TECHNOLOGY,"Information Technology"),
        (COMPUTER_SCIENCE,"Computer Science"),
        (CIVIL,"Civil")
    ]
    branch=models.CharField(max_length=50,choices=BRANCH_CHOICES)

    #Degree choices
    DIPLOMA="DP"
    BTECH="BT"
    MTECH="MT"
    DEGREE_CHOICES=[
        (DIPLOMA,"Diploma"),
        (BTECH,"B. Tech."),
        (MTECH,"M. Tech.")
    ]
    degree=models.CharField(max_length=50,choices=DEGREE_CHOICES)

    def __str__(self):
        return f"{self.first_name} {self.last_name} -{self.created.strftime('%d-%m-%Y')}"


class Category(models.Model):
    id=models.AutoField(primary_key=True)
    branch_name=models.CharField(max_length=50)

class Rack(models.Model):
    id=models.AutoField(primary_key=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    rack_num=models.IntegerField()

class Book(models.Model):
    barcode=models.CharField(primary_key=True,max_length=50)
    name=models.CharField(max_length=50,null=False)
    author=models.CharField(max_length=50,null=False)
    edition=models.CharField(max_length=50,null=False)
    category=models.ForeignKey(Category,null=True,blank=True,on_delete=models.CASCADE)
    available=models.BooleanField(null=False)

    def __str__(self) -> str:
        return f"{self.name} {self.barcode}"

class Rental_History(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    member=models.ForeignKey(Member,on_delete=models.DO_NOTHING)
    status=models.IntegerField(null=False)
    return_date=models.DateTimeField(auto_now_add=False,null=True)
    date=models.DateTimeField(auto_now_add=True)
    expected_return_date=models.DateTimeField(null=False)

class Active_Rented_Books(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    member=models.ForeignKey(Member,on_delete=models.CASCADE)
    status=models.IntegerField(null=False)
    date=models.DateTimeField(auto_now_add=True)
    expected_return_date=models.DateTimeField(null=False)

class Fine(models.Model):
    member=models.ForeignKey(Member,on_delete=models.CASCADE)
    amount=models.FloatField(default=0,null=False)

class Transaction_History(models.Model):
    id=models.AutoField(primary_key=True)
    member=models.ForeignKey(Member,on_delete=models.CASCADE)
    amount=models.FloatField(null=False)
    date=models.DateTimeField(auto_now_add=True)

library/forms.py
from .models import Profile
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm,U


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','prn','password1','password2','email']




class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['age', 'gender', 'weight', 'height']

library/views.py
from datetime import datetime, timedelta
from django.utils import timezone
import django
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.generic.base import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.hashers import check_password
import cv2
from . import utilities
from . import models
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.

def landingpage(request):
    return render(request, 'library/landingPage.html')


# @login_required
def homePage(request):
    print('abc')
    return render(request, 'library/homePage.html')


def teamPage(request):
    return render(request, 'library/teamPage.html')


@login_required
def search(request):
    query = request.GET["booksearch"]
    allBooks = models.Book.objects.all()
    print(allBooks, " all books")
    resultBooks = []
    matchedBooks = dict()
    for book in allBooks:
        if book.available == False:
            continue
        cnt = 0
        query_words = query.split(' ')
        for word in query_words:
            if word.lower() in book.name.lower():
                cnt += 1
        if book.name not in matchedBooks:
            resultBooks.append([cnt, book])
            matchedBooks[book.name] = 1
    resultBooks = sorted(resultBooks, key=lambda cnt_book: -cnt_book[0])
    print(resultBooks)
    if len(resultBooks) > 5:
        resultBooks[:] = resultBooks[:5]
    books = []
    for cnt_book in resultBooks:
        books.append([str(cnt_book[1]).rsplit(' ')[0], cnt_book[1].barcode])
    print(books)
    return render(request, 'library/searchpage.html', {"books": books, "query": query})


# @login_required
def rent(request, barcode):
    book = models.Book.objects.get(barcode=barcode)
    # mark book as unavailable
    book.available = False
    book.save()
    # add book in active_rented_books, rental_history
    member = models.Member.objects.get(user=request.user)
    status = 1
    expected_return_date = timezone.now() + timedelta(7)
    active_rented_book = models.Active_Rented_Books(book=book, member=member, status=status,
                                                    expected_return_date=expected_return_date)
    active_rented_book.save()
    rented_book = models.Rental_History(book=book, member=member, status=status,
                                        expected_return_date=expected_return_date)
    rented_book.save()
    messages.success(request, f"Book Rented Successfully!")
    return redirect('library:homePage')


@login_required
def return_book_superuser(request, barcode, prn):
    if request.user.is_superuser == False:
        return HttpResponse("Unauthorized access: Please continue with superuser account")
    book = models.Book.objects.get(barcode=barcode)
    rented_book = models.Active_Rented_Books.objects.get(book=book)
    member = models.Member.objects.get(prn=prn)
    # check for late return
    if rented_book.expected_return_date < timezone.now():
        # get original cost
        fine_l = models.Fine.objects.filter(member=member)
        if len(fine_l) == 0:
            fine = models.Fine(member=member, amount=50)
            fine.save()
        else:
            fine = fine_l[0]
            fine.amount += 50
            fine.save()
    book.available = True
    book.save()
    rented_book.delete()
    rent_history = models.Rental_History.objects.get(book=book, status=1)
    rent_history.status = 0
    rent_history.return_date = timezone.now()
    rent_history.save()
    return HttpResponse("Done")


class Login(View):

    def get(self, request, template_name='library/login.html'):
        return render(request, template_name)

    def post(self, request, template_name='library/login.html'):
        prn = request.POST['prn']
        password = request.POST['password']

        user = authenticate(username=prn, password=password)

        if user is not None:
            print(1)
            login(request, user)
            return redirect('library:homePage')
        else:
            args = {}
            args["error_message"] = "Invalid Credentials. Please Try Again."
            return render(request, template_name, args)


class Register(View):

    def get(self, request, template_name='library/signup.html'):
        return render(request, template_name)

    def post(self, request, template_name='library/signup.html'):
        username=request.POST['username']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        prn = request.POST['prn']
        password1 = request.POST['password']
        password2=password1
        email = request.POST['email']
        print(email)
        args = {}

        if password1 == password2:
            if User.objects.filter(email=email).exists():
                args["error_message"] = "Email Already Exists. Please Try Again."
                return render(request, template_name, args)
            elif User.objects.filter(username=username).exists():
                args["error_message"] = "Username Already Exists. Please Try Again."
                return render(request, template_name, args)
            else:
                user = User.objects.create_user(username=username,password=password1,email=email)
                user.save()
                print(user)
                member=models.Member(user=user,email=email,
                                    prn=prn,first_name=first_name,last_name=last_name)
                member.save()
                print(member)
                return redirect('library:login')

        else:
            args["error_message"] = "Passwords Don't Match. Please Try Again."
            return render(request, template_name, args)


class uploadBarcode(View):
    def get(self, request):
        if not request.user:
            return redirect('Login')
        return render(request, 'library/simple_upload.html')

    def post(self, request):
        if not request.user:
            return redirect('Login')
        myfile = request.FILES['myfile']
        print(1)
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        img = cv2.imread(filename)
        res = utilities.decode(img)
        # TODO
        if not res:
            return HttpResponseBadRequest()
        barcode = res["data"]
        messages.success(request, f"Book Rented Successfully!")
        return redirect('library:rent', barcode)


def Logout(request):
    logout(request)
    return redirect('/')


class viewProfile(View):
    def get(self, request, username, template_name="library/profile.html"):
        if request.user:
            member = models.Member.objects.filter(user=request.user)
            books = models.Active_Rented_Books.objects.filter(member=request.user.member)
            fine = models.Fine.objects.get(member=request.user.member)
            bookhistory = models.Rental_History.objects.filter(member=request.user.member).order_by('-date')
            parameters = {
                'member': member,
                "books": books,
                "fine": fine,
                "bookhistory": bookhistory
            }
            return render(request, template_name, parameters)
        else:
            redirect('library:login')


# Change password
class resetPassword(View):

    def get(self, request, template_name="changepassword.html"):
        return render(request, template_name)

    def post(self, request, template_name="changepassword.html"):
        currPassword = request.POST.get('currentPassword')
        newPassword = request.POST.get('newPassword')
        confPassword = request.POST.get('reNewPassword')

        try:
            matchcheck = check_password(currPassword, request.user.password)
            if matchcheck is False:
                err = {}
                err["error_message"] = "Entered Current Password is Incorrect. Please Retry."
                return render(request, template_name, err)
            if newPassword != confPassword:
                err = {}
                err["error_message"] = "Entered New Passwords don't Match. Please Retry."
                return render(request, template_name, err)
        except:
            err = {}
            err["error_message"] = "Refresh the Page to change the Password Again."
            return render(request, template_name, err)

        # U = User.objects.get(username=request.user.username)
        U = request.user
        U.set_password(newPassword)
        U.save()
        update_session_auth_hash(request, U)
        err = {}

        err["error_message"] = "Password changed successfully."
        return render(request, 'viewProfile.html')

library/templates/library/baseheadfoot.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'library/base.css' %}">

    {#    <link rel="shortcut icon" href="#"/>#}
    <script src="https://kit.fontawesome.com/df65e24a0c.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Library Management System</title>
    {% endif %}

</head>
<body>
<nav class="navbar navbar-dark navbar-expand-lg fixed-top" style="background-color: #005079c9;;padding: 20px 10px">
    <div class="container-lg">
        <a class="navbar-brand" href="#">
            <img src="{% static 'library/LMSlogo.png' %}" alt="" height="50px"
                 class="d-inline-block align-text-center"> WCELMS
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
             aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header" style="background-color: black; opacity: 1; color: white">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'library/LMSlogo.png' %}" alt="logo logo" height="50px"
                             class="d-inline-block align-text-top">
                    </a>
                </h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Close"><i class="fas fa-times"></i> &nbsp;&nbsp;
                </button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    {% if user.is_authenticated %}
                        <li class="nav-iteam">
                            <a class="nav-item nav-link"
                               href="{% url 'library:viewProfile' user.username %}">{{ user.username }}</a></li>
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:homePage' %}">Home</a></li>
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:team' %}">Team</a></li>
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:logout' %}">logout</a></li>

                    {% else %}
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:team' %}">Team</a></li>
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:login' %}">Login</a></li>
                        <li class="nav-iteam">
                            <a class="nav-item nav-link" href="{% url 'library:signup' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
<main role="main">
    {% if messages %}
        {% for message in messages %}
            <div style="position: relative;z-index: 10;top:95px"
                 class="alert alert-{{ message.tags }}"> {{ message }} </div>
        {% endfor %}
    {% endif %}
    {% block content %}

    {% endblock %}
</main>

{#Footer#}
<footer>
    <div class="footer_div">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-5 footer_col">
                    <div class="footer_about">
                        <img style="height: 40px;margin-bottom: 20px" class="footer_logo"
                             src="{% static 'library/LMSlogo.png' %}"
                             alt="">

                        <p>WCELMS is a library management system designed by third year students of Walchand College of
                            Engineering, Sangli of Electronics Department. It is Online interface for swift renting and
                            availability of books</p>
                    </div>
                </div>

                <div class="col-6 col-md-4 col-lg-3 footer_col">
                    <div class="footer_about">
                        <h3>QUICK LINKS</h3>
                        <p><a href="#">Team</a> <br><a href="#">Home</a> <br><a
                                href="#">Landing</a>
                            <br></p>
                    </div>
                </div>

                <div class="col-6 col-md-4 col-lg-2 footer_col">
                    <div class="footer_about">
                        <h3>SERVICES</h3>
                        <p>Rent Books<br>Online Interface<br>Scan Books</p>
                    </div>
                </div>

                <div class="col-12 col-md-4 col-lg-2 footer_col">
                    <div class="footer_about">
                        <h3>FOLLOW US</h3>
                        <p><a href="#"><i class="fab footer_icon fa-linkedin-in"></i></a> <a href="#"><i
                                class="fab footer_icon fa-facebook-f"></i></a> <a href="#"><i
                                class="fab footer_icon fa-instagram"></i></a></p>
                    </div>
                </div>
            </div>
            <div class="creator">
                <p>© 2022 WCELMS, All Rights Reserved</p>
            </div>
        </div>
    </div>
</footer>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

library/templates/library/homePage.html
{% extends "library/baseheadfoot.html" %}
{% load static %}

{% block content %}
    <script src="https://kit.fontawesome.com/df65e24a0c.js" crossorigin="anonymous"></script>
    <section class="home_head">
        {#        <div class="landing_head_text">#}
        {#            <h1>WCELMS</h1>#}
        {#            <h3>Library Management System</h3>#}
        {#        </div>#}
    </section>

    <section class="home_search">
        <h3>Search Books Now!</h3>
        <form action="{% url 'library:search' %}" method="GET">
            <div class="searchBox">
                <input class="searchInput" type="text" name="booksearch" placeholder="Search">
                <button class="searchButton" type="submit">
                    <i class="material-icons">
                        search
                    </i>
                </button>
            </div>
        </form>

    </section>
    <section class="toptrendingbooks container" style="margin: 120px auto; text-align: center">
        <h3 style="color: #216bac; font-weight: bold">Top Trending Books</h3>
        <br>
        <table class="table table-info table-striped">
            <thead>
            <tr>
                <th scope="col">Book Name</th>
                <th scope="col">Get Book</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Thermodynamics</td>
                <td><a href="#">Rent</a></td>
            </tr>
            <tr>
                <td>Applied Mathematics</td>
                <td><a href="#">Rent</a></td>
            </tr>
            <tr>
                <td>Mobile Communication Technology</td>
                <td><a href="#">Rent</a></td>
            </tr>
            <tr>
                <td>C Programming</td>
                <td><a href="#">Rent</a></td>
            </tr>
            <tr>
                <td>Data Structures And Algorithm</td>
                <td><a href="#">Rent</a></td>
            </tr>

            </tbody>
        </table>

    </section>

    <section class="file_upload" style="text-align: center">
        <h3>Upload QR Code here!</h3>
        <br>
        <form method="post" action="{% url 'library:uploadBarcode' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <input class="btn btn-info" type="file" name="myfile">
            <button class="btn btn-dark" type="submit">Upload</button>
        </form>

        {% if uploaded_file_url %}
            <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}
    </section>

{% endblock %}

library/templates/library/landingPage.html
{% extends "library/baseheadfoot.html" %}
{% load static %}

{% block content %}
    <script src="https://kit.fontawesome.com/df65e24a0c.js" crossorigin="anonymous"></script>
    <section class="landing_head">
        <div class="landing_head_text">
            <h1>WCELMS</h1>
            <h3>Library Management System</h3>
        </div>
    </section>

    <section class="landingloginregister">
        <div class="container" style="text-align: left">
            <div class="row justify-content-md-center">
                <div class="col-md-4 col-12 landing_login_col">
                    <a href="{% url 'library:login' %}">
                        <button class="button-63" role="button">Login Now!</button>
                    </a>
                    <hr>
                    <p>Login Now to use WCELMS! <br>
                        Best in class Library Management System</p>
                </div>
                <div class="col-md-4 col-12 landing_register_col">
                    <a href="{% url 'library:signup' %}">
                        <button class="button-64" role="button">Register!</button>
                    </a>
                    <hr>
                    <p>Register to use WCELMS! <br>
                        To experience smooth and easy library Rental and returns</p>
                </div>
            </div>
        </div>
    </section>

    <section class="landing_features">
        <h1>Why Choose WCELMS?</h1>
        <br>
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4">
                    <div class="landing_features_cols">
                        <img src="{% static 'library/smartphone.png' %}" alt="" width="60px">
                        <h2>Online Rental of Books</h2>
                        <p>Get all the books from library online! Check which books are available in library.</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="landing_features_cols">
                        <img src="{% static 'library/qr-code.png' %}" alt="" width="60px">
                        <h2>Scan & Go</h2>
                        <p>Scan your book from library and go! No human intervention. Contactless rental</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="landing_features_cols">
                        <img src="{% static 'library/payment-method.png' %}" alt="" width="60px">
                        <h2>Pay Online</h2>
                        <p>Got fines? No issues! No neet to visit library 100s of times. Pay it online!</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="landing_features_cols">
                        <img src="{% static 'library/market-trends.png' %}" alt="" width="60px">
                        <h2>Trending</h2>
                        <p>Get a list of trending books Now! See which are the top picks!</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="landing_features_cols">
                        <img src="{% static 'library/refresh.png' %}" alt="" width="60px">
                        <h2>History and Active</h2>
                        <p>Checkout all the active books you have along with past history</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

library/templates/library/login.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Todolist-Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'library/login.css' %}">
    </head>
    <body>
        <form class="login-form" action="{% url 'library:login' %}" method="POST">
            {%csrf_token%}
            <div class="login-form__content">
                <div class="login-form__header">Login to your account</div>
                <input class="login-form__input" type="text" name="prn" placeholder="Username">
                <input class="login-form__input" type="password" name="password" placeholder="Password">
                {% if error %}
                <p style="text-align:center">{{error}}</p>
                {%endif%}
                <button class="login-form__button" type="submit">Login</button>
                <div class="login-form__links">
                    
                </div>
            </div>
        </form>
    </body>
</html>

library/templates/library/searchpage.html
{% extends "library/baseheadfoot.html" %}
{% load static %}

{% block content %}
    <script src="https://kit.fontawesome.com/df65e24a0c.js" crossorigin="anonymous"></script>
    <section class="search_head">
    </section>

    <section class="home_search">
        <h3>Book Search Results : <u>{{ query }} </u></h3>

        {% if books %}
            <table class="table table-info table-striped table-md container hometable">
                <thead>
                <tr>
                    <th scope="col">Book Name</th>
                    <th scope="col">Get Book</th>
                </tr>
                </thead>
                <tbody>
                {% for book in books %}
                    <tr>
                        <td>{{ book.0 }}</td>
                        {% url "library:rent" barcode=book.1 as the_url %}
                        <td><a href="{{ the_url }}">Get Book</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

    </section>

{% endblock %}

library/templates/library/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Todolist-Signup</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'library/login.css' %}">
</head>
<body>


<form class="login-form" action="{% url 'library:signup' %}" method="POST">

    {% csrf_token %}
    <div class="login-form__content">
        <div class="login-form__header">Login to your account</div>
        <input class="login-form__input" type="text" name="username" placeholder="Username">
        <input class="login-form__input" type="password" name="password" placeholder="Password">

        <input class="login-form__input" type="text" name="firstname" placeholder="First Name">
        <input class="login-form__input" type="text" name="lastname" placeholder="Last Name">
        <input class="login-form__input" type="email" name="email" placeholder="Email ID">
        <input class="login-form__input" type="text" name="prn" placeholder="PRN">

        {% if error %}
            <p style="text-align:center">{{ error }}</p>
        {% endif %}
        <button class="login-form__button" type="submit">Signup</button>

        <div class="login-form__links">

        </div>
    </div>
</form>
</body>
</html>

library/templates/library/simple_upload.html
<html>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <button type="submit">Upload</button>
      </form>
    
      {% if uploaded_file_url %}
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
      {% endif %}
</html>

library/templates/library/teamPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>